apiVersion: v1 
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  ports: 
    - port: 3306
  selector:
     app: wordpress
     tier: MySQL
     clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: efs-mysql
   annotations: 
     volume.beta.kubernetes.io/Storage-class: "aws-efs"
spec:
  accessModes: 
     - ReadWriteMany
  resources: 
    requests: 
      storage: 10Gi

---


apiVersion: apps/v1
kind: Deployment
metadata: 
  name: wordpress-mysql
  labels: 
    app: wordpress
spec: 
  selector: 
    matchLabels:
      app: wordpress
      tier: MySQL
  strategy:
    type: Recreate
  template: 
    metadata:
       labels: 
         app:
         tier: MySQL
     spec: 
       containers:
       - image: MySQL:5.6
         name: MySQL
         env: 
         - name: MySQL_ROOT_PASSWORD
           valueFrom:
             sercetKeyRef:
                name: MySQL-pass
                key: password
          ports: 
          - containerPort: 3306
            name: MySQL
          volumwMounts: 
          - name: mysql-persistent-storage 
            mountPath: /var/lib/MySQL
        volumes: 
        - name: mysql-persistent-storage 
          persistentVolumeClaim: 
              claimName: efs-mysql 