apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata: 
  name: nfs-prov-role-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: wp-MySQL
roleRef: 
  kind: ClusterRole
  name: Cluster-admin
  apiGroup: rbac.authorization.k8s.io